baseURL = "https://anasbasheer.tech"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Anas Basheer"
description = "My Personal Portfolio"
# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"


[params]
  # uBlogger theme version
  version = "0.2.X"
  dateFormat = "January 02, 2006"

  [params.social]
    GitHub = 'an4s911'
    LinkedIn = 'an4s911'
    Instagram = 'an4s911'
    Twitter = 'an4s911'
    Email = 'admin@anasbasheer.tech'
  
  [params.search]
    enable = true
    type = "lunr"
    contentLength = 4000
    placeholder = "Search Site"
    maxResultLength = 10
    snippetLength = 30
    highlightTag = 'em'
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

  [params.header]
    desktopMode = 'fixed'

    [params.header.title]
      logo = '/favicon.ico'
      name = "Anas Basheer"
      pre = "    "

  [params.footer]
    custom = "Created by <a href='https://twitter.com/an4s911'>Anas Basheer</a>"
    enable = true
    hugo = false
    author = true
    copyright = true

  [params.home]
    [params.home.profile]
      enable = true
      gravatarEmail = "nasbas23@gmail.com"
      title = 'Anas Basheer'
      subtitle = 'Python Developer'
      social = true

    [params.home.posts]
      enable = true
      paginate = 6
      defaultHiddenFromPage = false

  [params.timeAgo]
    enable = "true"

  [params.page]
    [params.page.share]
      enable = true
      Twitter = true
      WhatsApp = true
      LinkedIn = true
      Pocket = true

  [params.comment]
    enable = true
    [params.comment.remark42]
      enable = false
    [params.comment.disqus]
      enable = true
      shortname = 'anas-basheer'
    [params.comment.utterances]
      enable = true
      repo = 'an4s911/blog-site'
      lightTheme = 'github-light'
      darkTheme = 'github-dark'

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "posts/"
    # title will be shown when you hover on this menu link
    title = "Blog Posts"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = 'issues'
    name = "Issues"
    url = "issues/"
    title = "Issues"
    weight = 4

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration
    noClasses = false

# Search
[outputs]
  home = ["HTML", "RSS", "JSON"]

#Permalinks config
[Permalinks]
  posts = ":year/:month/:filename"