baseURL = "https://anasbasheer.tech"
defaultContentLanguage = "en"
description = "My Personal Portfolio"
languageCode = "en"
theme = "LoveIt"
title = "Anas Basheer"
[Permalinks]
posts = ":filename"
[markup.highlight]
noClasses = false
[[menu.main]]
identifier = "posts"
name = "Posts"
post = ""
pre = ""
title = "Blog Posts"
url = "posts/"
weight = 2
[[menu.main]]
identifier = "tags"
name = "Tags"
post = ""
pre = ""
title = ""
url = "tags/"
weight = 3
[[menu.main]]
identifier = "categories"
name = "Categories"
post = ""
pre = ""
title = ""
url = "categories/"
weight = 4
[[menu.main]]
identifier = "issues"
name = "Issues"
title = "Issues"
url = "issues/"
weight = 5
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
dateFormat = "January 02, 2006"
defaultTheme = "auto"
version = "0.2.X"
[params.footer]
author = true
copyright = true
custom = "Created by <a href='https://twitter.com/an4s911'>Anas Basheer</a>"
enable = true
hugo = false
[params.header]
desktopMode = "fixed"
mobileMode = "fixed"
[params.header.title]
logo = ""
name = "Anas Basheer"
pre = "    "
[params.home.posts]
defaultHiddenFromPage = false
enable = true
paginate = 6
[params.home.profile]
enable = true
gravatarEmail = "nasbas23@gmail.com"
social = true
subtitle = "Python Developer"
title = "Anas Basheer"
[params.list]
dateFormat = "01-02"
paginate = 20
rss = 10
[params.page]
fontawesome = true
fraction = true
hiddenFromHomePage = false
hiddenFromSearch = false
lightgallery = false
linkToMarkdown = true
rssFullText = false
ruby = true
twemoji = false
[params.page.comment]
enable = true
[params.page.comment.disqus]
enable = true
shortname = "anas-basheer"
[params.page.comment.utterances]
darkTheme = "github-dark"
enable = true
lightTheme = "github-light"
repo = "an4s911/blog-site"
[params.page.share]
LinkedIn = true
Pocket = true
Twitter = true
WhatsApp = true
enable = true
[params.page.toc]
auto = true
enable = true
keepStatic = false
[params.search]
absoluteURL = false
contentLength = 4000
enable = true
highlightTag = "em"
maxResultLength = 10
placeholder = "Search Site"
snippetLength = 30
type = "lunr"
[params.search.algolia]
appID = ""
index = ""
searchKey = ""
[params.section]
dateFormat = "01-02"
paginate = 20
rss = 10
[params.social]
Email = "admin@anasbasheer.tech"
GitHub = "an4s911"
Instagram = "an4s911"
LinkedIn = "an4s911"
Twitter = "an4s911"
[params.timeAgo]
enable = "true"
[params.typeit]
cursorChar = "|"
cursorSpeed = 1000
duration = -1
speed = 100
